# Generated by Django 4.1.2 on 2022-10-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='external_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='internal_page',
            field=models.ForeignKey(blank=True, help_text='Sélectionner une page interne', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_image',
            field=models.ForeignKey(help_text='Choisir une image pour ce service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
