# Generated by Django 4.1.2 on 2022-10-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Quiquia dolorem adipisci dolorem ipsum sed. Voluptatem numquam labore ipsum. Porro modi labore etincidunt. Non aliquam neque ipsum. Porro dolore porro ipsum quisquam quaerat dolore. Est eius sit eius dolorem sit dolor. Dolorem ipsum numquam modi modi dolore numquam voluptatem. Adipisci eius dolorem quiquia ut amet velit labore. Ipsum consectetur est non est sed sed quiquia. Amet aliquam aliquam quisquam tempora labore.', max_length=500),
        ),
    ]
