# Generated by Django 4.1.2 on 2022-10-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Eius modi voluptatem quiquia modi. Sed eius porro est consectetur quaerat dolore aliquam. Est quisquam quaerat modi. Magnam porro eius modi tempora est dolorem etincidunt. Labore consectetur voluptatem porro numquam numquam sit consectetur. Etincidunt ipsum magnam amet porro voluptatem quiquia neque. Amet dolore magnam sit eius. Consectetur sit sed consectetur. Labore aliquam est dolorem aliquam ut adipisci ut.', max_length=500),
        ),
    ]
