# Generated by Django 4.1.2 on 2022-10-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Quisquam labore dolor ut. Porro dolorem ipsum sed etincidunt. Non ipsum neque porro dolor ut quisquam. Consectetur dolore magnam ut dolore dolore. Adipisci neque sit quaerat neque. Neque dolore neque numquam dolore tempora. Quaerat numquam dolorem non dolore magnam dolore. Amet neque ipsum eius eius amet est modi.', max_length=500),
        ),
    ]
