# Generated by Django 4.1.2 on 2022-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Quaerat ipsum non sed. Neque numquam amet dolore sed ipsum dolorem modi. Non neque sit eius. Consectetur modi quisquam dolor adipisci dolor neque. Adipisci voluptatem labore aliquam tempora eius. Velit quiquia est amet. Adipisci quaerat adipisci ut aliquam tempora. Porro magnam quiquia quisquam sed. Consectetur dolorem eius tempora.', max_length=500),
        ),
    ]
