# Generated by Django 4.1.2 on 2022-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Ipsum voluptatem tempora sed est tempora ipsum sit. Dolor labore neque ipsum labore quaerat. Voluptatem dolorem amet dolorem dolor labore dolorem. Tempora quaerat adipisci quaerat ut eius. Numquam labore sed ut. Dolorem dolorem tempora ut dolore velit labore. Amet non modi sed. Consectetur numquam velit neque quiquia aliquam. Dolor porro numquam sit adipisci modi.', max_length=500),
        ),
    ]
