# Generated by Django 4.1.2 on 2022-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Aliquam eius tempora ipsum quisquam labore dolore sed. Quisquam velit dolor dolor modi porro. Consectetur eius ut adipisci voluptatem. Etincidunt numquam voluptatem magnam dolorem. Quisquam consectetur quiquia est eius magnam. Numquam quiquia eius quaerat est quiquia voluptatem. Dolor amet sed dolore quisquam.', max_length=500),
        ),
    ]
