# Generated by Django 4.1.2 on 2022-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0010_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page', 'verbose_name_plural': 'Flex Pages'},
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Quiquia aliquam consectetur velit numquam porro. Voluptatem est voluptatem est modi. Quiquia labore magnam dolor dolorem non dolorem. Quiquia etincidunt velit quisquam tempora voluptatem dolor. Etincidunt consectetur velit dolore. Ut numquam eius labore. Voluptatem quisquam eius quisquam etincidunt ut non. Sit non ut neque neque magnam. Etincidunt quiquia dolorem velit.', max_length=500),
        ),
    ]
