# Generated by Django 4.1.2 on 2022-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_alter_flexpage_options_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Adipisci velit numquam aliquam quiquia numquam quaerat. Consectetur aliquam etincidunt labore magnam modi. Velit numquam ut labore. Velit magnam aliquam ipsum. Magnam quiquia consectetur quisquam. Porro sit dolore est velit tempora dolorem. Quiquia dolore consectetur velit adipisci aliquam velit.', max_length=500),
        ),
    ]
