# Generated by Django 4.1.2 on 2022-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0012_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Est tempora est sed modi dolorem dolore. Dolorem quiquia numquam numquam modi quiquia velit sit. Tempora quisquam quiquia quaerat sit non neque sed. Voluptatem porro non ut sed non. Velit quisquam dolorem ut ipsum quiquia. Est non modi voluptatem modi labore ipsum. Ut dolore sit sed.', max_length=500),
        ),
    ]
