# Generated by Django 4.1.2 on 2022-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0013_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Ut magnam dolorem aliquam modi aliquam adipisci modi. Voluptatem ipsum non ut dolore quaerat eius. Ipsum numquam etincidunt tempora modi velit. Sed numquam modi velit. Voluptatem consectetur sed quisquam non adipisci sit porro. Voluptatem labore eius porro quisquam labore.', max_length=500),
        ),
    ]
