# Generated by Django 4.1.2 on 2022-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0014_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Dolore quiquia magnam sit porro velit sit. Magnam aliquam neque eius aliquam non adipisci etincidunt. Quiquia quiquia eius sit non velit consectetur numquam. Neque amet numquam ut tempora aliquam sed. Porro magnam non ipsum quaerat porro non. Non eius amet eius dolorem velit consectetur. Sit quaerat magnam consectetur.', max_length=500),
        ),
    ]
