# Generated by Django 4.1.2 on 2022-10-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0015_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Dolore voluptatem eius ipsum sit non dolorem tempora. Adipisci amet ut amet dolore non. Consectetur amet est velit est quaerat. Velit ut sit amet amet est sed. Non est est porro aliquam ut est. Etincidunt etincidunt magnam ipsum adipisci modi non adipisci. Non tempora non consectetur aliquam. Quaerat voluptatem neque eius magnam. Non neque non numquam ut neque adipisci sed. Velit eius etincidunt amet sed est adipisci.', max_length=500),
        ),
    ]
