# Generated by Django 4.1.2 on 2022-10-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0016_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Voluptatem quaerat porro quiquia modi tempora etincidunt est. Ipsum numquam porro velit sed amet dolor labore. Est neque dolore amet dolorem dolor tempora quiquia. Est quisquam magnam tempora neque. Dolore dolor tempora quisquam sit quisquam adipisci. Sed quiquia amet consectetur magnam quaerat quiquia. Velit sit quiquia sit neque ut sit velit.', max_length=500),
        ),
    ]
