# Generated by Django 4.1.2 on 2022-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0017_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Magnam consectetur neque etincidunt quaerat dolor. Tempora etincidunt quisquam velit magnam. Tempora non numquam consectetur. Dolorem sit adipisci velit voluptatem. Dolorem etincidunt consectetur tempora aliquam. Modi porro sed consectetur sed voluptatem.', max_length=500),
        ),
    ]
