# Generated by Django 4.1.2 on 2022-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0018_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Labore porro sit quaerat amet ipsum dolorem. Dolore ut sit quaerat. Numquam etincidunt porro quiquia voluptatem. Adipisci labore ipsum porro ipsum dolorem tempora numquam. Velit porro quaerat dolore quiquia. Numquam adipisci quisquam aliquam neque.', max_length=500),
        ),
    ]
