# Generated by Django 4.1.2 on 2022-10-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0020_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Dolorem est dolore adipisci. Velit modi dolore dolorem non consectetur. Non porro velit neque est velit. Est neque magnam dolorem non quaerat tempora. Labore est amet ipsum est labore non dolor. Est etincidunt modi non. Sed labore sed est non quisquam.', max_length=500),
        ),
    ]
