# Generated by Django 4.1.2 on 2022-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0022_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Dolore adipisci labore dolore aliquam quisquam. Consectetur ipsum adipisci amet dolorem quisquam ipsum quiquia. Neque non dolorem consectetur. Sed quisquam aliquam ipsum dolore neque. Magnam modi adipisci est eius aliquam neque. Sed dolor consectetur dolor eius numquam. Consectetur aliquam sed porro est etincidunt quaerat.', max_length=500),
        ),
    ]
