# Generated by Django 4.1.2 on 2022-10-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0025_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Porro consectetur quiquia non magnam eius labore sed. Sit quisquam adipisci adipisci amet numquam. Numquam velit neque aliquam consectetur consectetur voluptatem velit. Quaerat sed sit est numquam. Dolorem voluptatem porro adipisci dolor labore aliquam numquam. Neque velit sit adipisci voluptatem amet dolore dolore. Etincidunt adipisci ut ipsum.', max_length=500),
        ),
    ]
