# Generated by Django 4.1.2 on 2022-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0026_alter_flexpage_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='lorem',
            field=models.TextField(blank=True, default='Dolor quisquam numquam sed. Dolor tempora consectetur numquam numquam. Labore tempora numquam quisquam quisquam. Adipisci est tempora magnam. Voluptatem voluptatem amet sed. Dolor dolore quisquam etincidunt dolor quiquia numquam. Amet est quiquia ut quisquam ipsum tempora. Amet dolore aliquam labore porro quisquam aliquam. Quisquam tempora aliquam modi quaerat dolor sed etincidunt.', max_length=500),
        ),
    ]
