# Generated by Django 4.1.2 on 2022-10-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonials_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Tesgtimonials'},
        ),
    ]
